/**
 * ============================================================================
 * EXERCISE: Robinhood-Style Stock Trading REST API Contracts (TypeScript)
 * ============================================================================
 * Domain Problem:
 * You are defining the strongly-typed contracts for a retail stock brokerage
 * REST API. These types define the wire formats, request parameter locations,
 * and response envelopes for market data quotes and trade order execution.
 *
 * 🎯 Learning Objectives:
 * 1. Express RESTful resources and parameter locations using TypeScript.
 * 2. Financial precision: model prices/quantities without IEEE-754 float drift.
 * 3. Idempotent mutations: typing Idempotency-Key headers for financial writes.
 * 4. Auth-scoped resource identity: mitigating IDOR in user order history.
 * ============================================================================
 */

// ----------------------------------------------------------------------------
// 1. Foundational Enums & Precision Types
// ----------------------------------------------------------------------------

/**
 * Monetary representation:
 * Always avoid raw JavaScript numbers for currency or pricing calculations.
 * Strings (e.g. "185.50") or integer cents prevent IEEE-754 precision loss.
 */
export type DecimalString = string; // e.g. "185.5000" (fixed precision)
export type ISOTimestamp = string;  // e.g. "2026-09-18T13:30:00.000Z"

export type OrderSide = "BUY" | "SELL";

export type OrderType =
  | "MARKET"     // Executed immediately at current prevailing market price
  | "LIMIT"      // Executed only at specified limit price or better
  | "STOP_LOSS"; // Triggered when stock falls to specified stop price

export type TimeInForce =
  | "DAY" // Valid until end of regular trading day
  | "GTC"; // Good 'Til Cancelled (typically up to 90 days)

export type OrderStatus =
  | "PENDING"          // Order received and validated; enqueued for matching
  | "SUBMITTED"        // Forwarded to broker/exchange
  | "PARTIALLY_FILLED" // Partial quantity executed
  | "FILLED"           // Completed fill for total quantity
  | "CANCELLED"        // Cancelled by user or broker before execution
  | "REJECTED"         // Rejected due to risk limits, buying power, or halts
  | "EXPIRED";         // Time-in-force elapsed without full fill


// ----------------------------------------------------------------------------
// 2. Action 1: viewStockQuote(symbol)
// ----------------------------------------------------------------------------

export interface GetStockQuoteParams {
  /** Symbol path parameter, e.g. "AAPL" */
  symbol: string;
}

export interface StockQuoteResponse {
  symbol: string;
  currency: "USD";
  /** Current prevailing market trade price */
  currentPrice: DecimalString;
  /** Highest price a buyer is willing to pay */
  bidPrice: DecimalString;
  bidSize: number;
  /** Lowest price a seller is willing to accept */
  askPrice: DecimalString;
  askSize: number;
  /** Total shares traded today */
  volume: number;
  /** Trading day open, high, low, previous close */
  dayHigh: DecimalString;
  dayLow: DecimalString;
  previousClose: DecimalString;
  /** Timestamp when market data snapshot was generated */
  updatedAt: ISOTimestamp;
}


// ----------------------------------------------------------------------------
// 3. Action 2: viewStockQuotes(List<symbol>)
// ----------------------------------------------------------------------------

export interface GetBatchStockQuotesQuery {
  /**
   * Comma-separated list of ticker symbols, e.g. "AAPL,MSFT,GOOGL"
   * Alternative: repeated query keys (e.g. `symbol=AAPL&symbol=MSFT`)
   */
  symbols: string;
}

export interface BatchStockQuotesResponse {
  /** Map of symbol -> quote, or array of quotes */
  quotes: Record<string, StockQuoteResponse>;
  /** Symbols that could not be resolved or are invalid/untraded */
  unresolvedSymbols: string[];
  generatedAt: ISOTimestamp;
}


// ----------------------------------------------------------------------------
// 4. Action 3: placeOrder(symbol, quantity, orderType)
// ----------------------------------------------------------------------------

export interface PlaceOrderHeaders {
  /**
   * UUID v4 generated by client. If network times out, retrying with the same
   * key will safely replay the original order response instead of placing a 2nd trade.
   */
  "Idempotency-Key": string;
  Authorization: `Bearer ${string}`;
}

export interface PlaceOrderRequest {
  symbol: string;
  side: OrderSide;
  quantity: number; // Share count (integer for whole shares, DecimalString for fractional)
  orderType: OrderType;
  /** Required if orderType is LIMIT or STOP_LOSS */
  limitPrice?: DecimalString;
  stopPrice?: DecimalString;
  timeInForce: TimeInForce;
}

export interface PlaceOrderResponse {
  orderId: string;
  userId: string;
  symbol: string;
  side: OrderSide;
  orderType: OrderType;
  quantity: number;
  limitPrice: DecimalString | null;
  status: OrderStatus;
  createdAt: ISOTimestamp;
}


// ----------------------------------------------------------------------------
// 5. Action 4: viewOrder(orderId)
// ----------------------------------------------------------------------------

export interface GetOrderParams {
  orderId: string;
}

export interface OrderFill {
  fillId: string;
  shares: number;
  price: DecimalString;
  executedAt: ISOTimestamp;
}

export interface OrderDetailResponse extends PlaceOrderResponse {
  filledQuantity: number;
  averageExecutionPrice: DecimalString | null;
  commissionFees: DecimalString;
  fills: OrderFill[];
  updatedAt: ISOTimestamp;
}


// ----------------------------------------------------------------------------
// 6. Action 5: viewAllOrders(userId)
// ----------------------------------------------------------------------------

export interface ListOrdersQuery {
  /** Optional filter by order status */
  status?: OrderStatus;
  /** Optional filter by ticker symbol */
  symbol?: string;
  /** Pagination page limit (default 20, max 100) */
  limit?: number;
  /** Opaque cursor for key-based pagination */
  cursor?: string;
}

export interface ListOrdersResponse {
  orders: OrderDetailResponse[];
  /** Next cursor to pass in query params to fetch subsequent page */
  nextCursor: string | null;
  hasMore: boolean;
}


// ----------------------------------------------------------------------------
// 7. REST Route Definition Map (The Full REST API Catalog)
// ----------------------------------------------------------------------------

/**
 * [STEP 7 DRILL]: Review the REST route definitions below.
 * Notice how HTTP methods, paths, and parameter placements map cleanly.
 */
export interface TradingApiRoutes {
  /**
   * Action 1: viewStockQuote
   * GET /api/v1/stocks/:symbol/quote (or GET /api/v1/quotes/:symbol)
   */
  "GET /api/v1/stocks/:symbol/quote": {
    pathParams: GetStockQuoteParams;
    queryParams: never;
    requestBody: never;
    response: StockQuoteResponse;
    statusCodes: 200 | 404;
  };

  /**
   * Action 2: viewStockQuotes
   * GET /api/v1/quotes?symbols=AAPL,MSFT
   */
  "GET /api/v1/quotes": {
    pathParams: never;
    queryParams: GetBatchStockQuotesQuery;
    requestBody: never;
    response: BatchStockQuotesResponse;
    statusCodes: 200 | 400;
  };

  /**
   * Action 3: placeOrder
   * POST /api/v1/orders
   */
  "POST /api/v1/orders": {
    headers: PlaceOrderHeaders;
    pathParams: never;
    queryParams: never;
    requestBody: PlaceOrderRequest;
    response: PlaceOrderResponse;
    statusCodes: 201 | 400 | 401 | 409 | 422;
  };

  /**
   * Action 4: viewOrder
   * GET /api/v1/orders/:orderId
   */
  "GET /api/v1/orders/:orderId": {
    pathParams: GetOrderParams;
    queryParams: never;
    requestBody: never;
    response: OrderDetailResponse;
    statusCodes: 200 | 401 | 404;
  };

  /**
   * Action 5: viewAllOrders (Client / Self Scoped)
   * GET /api/v1/orders (Uses authenticated Bearer token, avoids IDOR vulnerabilities)
   */
  "GET /api/v1/orders": {
    pathParams: never;
    queryParams: ListOrdersQuery;
    requestBody: never;
    response: ListOrdersResponse;
    statusCodes: 200 | 401;
  };

  /**
   * Action 5 (Alternative): viewAllOrders (Admin / Back-Office Scoped)
   * GET /api/v1/users/:userId/orders (Only for admin role with audit logging)
   */
  "GET /api/v1/users/:userId/orders": {
    pathParams: { userId: string };
    queryParams: ListOrdersQuery;
    requestBody: never;
    response: ListOrdersResponse;
    statusCodes: 200 | 401 | 403;
  };
}
